export type UntypedProps = {
    _alignContent: string
    _alignItems: string
    _alignSelf: string
    _alignmentBaseline: string
    _all: string
    _animation: string
    _animationDelay: string
    _animationDirection: string
    _animationDuration: string
    _animationFillMode: string
    _animationIterationCount: string
    _animationName: string
    _animationPlayState: string
    _animationTimingFunction: string
    _appearance: string
    _aspectRatio: string
    _azimuth: string
    _backfaceVisibility: string
    _background: string
    _backgroundAttachment: string
    _backgroundBlendMode: string
    _backgroundClip: string
    _backgroundColor: string
    _backgroundImage: string
    _backgroundOrigin: string
    _backgroundPosition: string
    _backgroundRepeat: string
    _backgroundSize: string
    _baselineShift: string
    _baselineSource: string
    _blockEllipsis: string
    _blockSize: string
    _blockStep: string
    _blockStepAlign: string
    _blockStepInsert: string
    _blockStepRound: string
    _blockStepSize: string
    _bookmarkLabel: string
    _bookmarkLevel: string
    _bookmarkState: string
    _border: string
    _borderBlock: string
    _borderBlockColor: string
    _borderBlockEnd: string
    _borderBlockEndColor: string
    _borderBlockEndStyle: string
    _borderBlockEndWidth: string
    _borderBlockStart: string
    _borderBlockStartColor: string
    _borderBlockStartStyle: string
    _borderBlockStartWidth: string
    _borderBlockStyle: string
    _borderBlockWidth: string
    _borderBottom: string
    _borderBottomColor: string
    _borderBottomLeftRadius: string
    _borderBottomRightRadius: string
    _borderBottomStyle: string
    _borderBottomWidth: string
    _borderBoundary: string
    _borderCollapse: string
    _borderColor: string
    _borderEndEndRadius: string
    _borderEndStartRadius: string
    _borderImage: string
    _borderImageOutset: string
    _borderImageRepeat: string
    _borderImageSlice: string
    _borderImageSource: string
    _borderImageWidth: string
    _borderInline: string
    _borderInlineColor: string
    _borderInlineEnd: string
    _borderInlineEndColor: string
    _borderInlineEndStyle: string
    _borderInlineEndWidth: string
    _borderInlineStart: string
    _borderInlineStartColor: string
    _borderInlineStartStyle: string
    _borderInlineStartWidth: string
    _borderInlineStyle: string
    _borderInlineWidth: string
    _borderLeft: string
    _borderLeftColor: string
    _borderLeftStyle: string
    _borderLeftWidth: string
    _borderRadius: string
    _borderRight: string
    _borderRightColor: string
    _borderRightStyle: string
    _borderRightWidth: string
    _borderSpacing: string
    _borderStartEndRadius: string
    _borderStartStartRadius: string
    _borderStyle: string
    _borderTop: string
    _borderTopColor: string
    _borderTopLeftRadius: string
    _borderTopRightRadius: string
    _borderTopStyle: string
    _borderTopWidth: string
    _borderWidth: string
    _bottom: string
    _boxDecorationBreak: string
    _boxShadow: string
    _boxSizing: string
    _boxSnap: string
    _breakAfter: string
    _breakBefore: string
    _breakInside: string
    _captionSide: string
    _caret: string
    _caretColor: string
    _caretShape: string
    _chains: string
    _clear: string
    _clip: string
    _clipPath: string
    _clipRule: string
    _color: string
    _colorAdjust: string
    _colorInterpolationFilters: string
    _colorScheme: string
    _columnCount: string
    _columnFill: string
    _columnGap: string
    _columnRule: string
    _columnRuleColor: string
    _columnRuleStyle: string
    _columnRuleWidth: string
    _columnSpan: string
    _columnWidth: string
    _columns: string
    _contain: string
    _containIntrinsicSize: string
    _content: string
    _contentVisibility: string
    _continue: string
    _counterIncrement: string
    _counterReset: string
    _counterSet: string
    _cue: string
    _cueAfter: string
    _cueBefore: string
    _cursor: string
    _direction: string
    _display: string
    _dominantBaseline: string
    _elevation: string
    _emptyCells: string
    _fill: string
    _fillBreak: string
    _fillColor: string
    _fillImage: string
    _fillOpacity: string
    _fillOrigin: string
    _fillPosition: string
    _fillRepeat: string
    _fillRule: string
    _fillSize: string
    _filter: string
    _flex: string
    _flexBasis: string
    _flexDirection: string
    _flexFlow: string
    _flexGrow: string
    _flexShrink: string
    _flexWrap: string
    _float: string
    _floatDefer: string
    _floatOffset: string
    _floatReference: string
    _floodColor: string
    _floodOpacity: string
    _flow: string
    _flowFrom: string
    _flowInto: string
    _font: string
    _fontFamily: string
    _fontFeatureSettings: string
    _fontKerning: string
    _fontLanguageOverride: string
    _fontOpticalSizing: string
    _fontPalette: string
    _fontSize: string
    _fontSizeAdjust: string
    _fontStretch: string
    _fontStyle: string
    _fontSynthesis: string
    _fontSynthesisSmallCaps: string
    _fontSynthesisStyle: string
    _fontSynthesisWeight: string
    _fontVariant: string
    _fontVariantAlternates: string
    _fontVariantCaps: string
    _fontVariantEastAsian: string
    _fontVariantEmoji: string
    _fontVariantLigatures: string
    _fontVariantNumeric: string
    _fontVariantPosition: string
    _fontVariationSettings: string
    _fontWeight: string
    _footnoteDisplay: string
    _footnotePolicy: string
    _forcedColorAdjust: string
    _gap: string
    _glyphOrientationVertical: string
    _grid: string
    _gridArea: string
    _gridAutoColumns: string
    _gridAutoFlow: string
    _gridAutoRows: string
    _gridColumn: string
    _gridColumnEnd: string
    _gridColumnStart: string
    _gridRow: string
    _gridRowEnd: string
    _gridRowStart: string
    _gridTemplate: string
    _gridTemplateAreas: string
    _gridTemplateColumns: string
    _gridTemplateRows: string
    _hangingPunctuation: string
    _height: string
    _hyphenateCharacter: string
    _hyphenateLimitChars: string
    _hyphenateLimitLast: string
    _hyphenateLimitLines: string
    _hyphenateLimitZone: string
    _hyphens: string
    _imageOrientation: string
    _imageRendering: string
    _imageResolution: string
    _initialLetter: string
    _initialLetterAlign: string
    _initialLetterWrap: string
    _inlineSize: string
    _inlineSizing: string
    _inset: string
    _insetBlock: string
    _insetBlockEnd: string
    _insetBlockStart: string
    _insetInline: string
    _insetInlineEnd: string
    _insetInlineStart: string
    _isolation: string
    _justifyContent: string
    _justifyItems: string
    _justifySelf: string
    _leadingTrim: string
    _left: string
    _letterSpacing: string
    _lightingColor: string
    _lineBreak: string
    _lineClamp: string
    _lineGrid: string
    _lineHeight: string
    _lineHeightStep: string
    _linePadding: string
    _lineSnap: string
    _listStyle: string
    _listStyleImage: string
    _listStylePosition: string
    _listStyleType: string
    _margin: string
    _marginBlock: string
    _marginBlockEnd: string
    _marginBlockStart: string
    _marginBottom: string
    _marginBreak: string
    _marginInline: string
    _marginInlineEnd: string
    _marginInlineStart: string
    _marginLeft: string
    _marginRight: string
    _marginTop: string
    _marginTrim: string
    _marker: string
    _markerEnd: string
    _markerKnockoutLeft: string
    _markerKnockoutRight: string
    _markerMid: string
    _markerPattern: string
    _markerSegment: string
    _markerSide: string
    _markerStart: string
    _mask: string
    _maskBorder: string
    _maskBorderMode: string
    _maskBorderOutset: string
    _maskBorderRepeat: string
    _maskBorderSlice: string
    _maskBorderSource: string
    _maskBorderWidth: string
    _maskClip: string
    _maskComposite: string
    _maskImage: string
    _maskMode: string
    _maskOrigin: string
    _maskPosition: string
    _maskRepeat: string
    _maskSize: string
    _maskType: string
    _maxBlockSize: string
    _maxHeight: string
    _maxInlineSize: string
    _maxLines: string
    _maxWidth: string
    _minBlockSize: string
    _minHeight: string
    _minInlineSize: string
    _minIntrinsicSizing: string
    _minWidth: string
    _mixBlendMode: string
    _navDown: string
    _navLeft: string
    _navRight: string
    _navUp: string
    _objectFit: string
    _objectPosition: string
    _offset: string
    _offsetAnchor: string
    _offsetDistance: string
    _offsetPath: string
    _offsetPosition: string
    _offsetRotate: string
    _opacity: string
    _order: string
    _orphans: string
    _outline: string
    _outlineColor: string
    _outlineOffset: string
    _outlineStyle: string
    _outlineWidth: string
    _overflow: string
    _overflowAnchor: string
    _overflowBlock: string
    _overflowClipMargin: string
    _overflowInline: string
    _overflowWrap: string
    _overflowX: string
    _overflowY: string
    _overscrollBehavior: string
    _overscrollBehaviorBlock: string
    _overscrollBehaviorInline: string
    _overscrollBehaviorX: string
    _overscrollBehaviorY: string
    _padding: string
    _paddingBlock: string
    _paddingBlockEnd: string
    _paddingBlockStart: string
    _paddingBottom: string
    _paddingInline: string
    _paddingInlineEnd: string
    _paddingInlineStart: string
    _paddingLeft: string
    _paddingRight: string
    _paddingTop: string
    _page: string
    _pageBreakAfter: string
    _pageBreakBefore: string
    _pageBreakInside: string
    _pause: string
    _pauseAfter: string
    _pauseBefore: string
    _perspective: string
    _perspectiveOrigin: string
    _pitch: string
    _pitchRange: string
    _placeContent: string
    _placeItems: string
    _placeSelf: string
    _playDuring: string
    _position: string
    _propertyName: string
    _quotes: string
    _regionFragment: string
    _resize: string
    _rest: string
    _restAfter: string
    _restBefore: string
    _richness: string
    _right: string
    _rotate: string
    _rowGap: string
    _rubyAlign: string
    _rubyMerge: string
    _rubyOverhang: string
    _rubyPosition: string
    _running: string
    _scale: string
    _scrollBehavior: string
    _scrollMargin: string
    _scrollMarginBlock: string
    _scrollMarginBlockEnd: string
    _scrollMarginBlockStart: string
    _scrollMarginBottom: string
    _scrollMarginInline: string
    _scrollMarginInlineEnd: string
    _scrollMarginInlineStart: string
    _scrollMarginLeft: string
    _scrollMarginRight: string
    _scrollMarginTop: string
    _scrollPadding: string
    _scrollPaddingBlock: string
    _scrollPaddingBlockEnd: string
    _scrollPaddingBlockStart: string
    _scrollPaddingBottom: string
    _scrollPaddingInline: string
    _scrollPaddingInlineEnd: string
    _scrollPaddingInlineStart: string
    _scrollPaddingLeft: string
    _scrollPaddingRight: string
    _scrollPaddingTop: string
    _scrollSnapAlign: string
    _scrollSnapStop: string
    _scrollSnapType: string
    _scrollbarColor: string
    _scrollbarGutter: string
    _scrollbarWidth: string
    _shapeImageThreshold: string
    _shapeInside: string
    _shapeMargin: string
    _shapeOutside: string
    _spatialNavigationAction: string
    _spatialNavigationContain: string
    _spatialNavigationFunction: string
    _speak: string
    _speakAs: string
    _speakHeader: string
    _speakNumeral: string
    _speakPunctuation: string
    _speechRate: string
    _stress: string
    _stringSet: string
    _stroke: string
    _strokeAlign: string
    _strokeAlignment: string
    _strokeBreak: string
    _strokeColor: string
    _strokeDashCorner: string
    _strokeDashJustify: string
    _strokeDashadjust: string
    _strokeDasharray: string
    _strokeDashcorner: string
    _strokeDashoffset: string
    _strokeImage: string
    _strokeLinecap: string
    _strokeLinejoin: string
    _strokeMiterlimit: string
    _strokeOpacity: string
    _strokeOrigin: string
    _strokePosition: string
    _strokeRepeat: string
    _strokeSize: string
    _strokeWidth: string
    _tabSize: string
    _tableLayout: string
    _textAlign: string
    _textAlignAll: string
    _textAlignLast: string
    _textCombineUpright: string
    _textDecoration: string
    _textDecorationColor: string
    _textDecorationLine: string
    _textDecorationSkip: string
    _textDecorationSkipBox: string
    _textDecorationSkipInk: string
    _textDecorationSkipInset: string
    _textDecorationSkipSelf: string
    _textDecorationSkipSpaces: string
    _textDecorationStyle: string
    _textDecorationThickness: string
    _textEdge: string
    _textEmphasis: string
    _textEmphasisColor: string
    _textEmphasisPosition: string
    _textEmphasisSkip: string
    _textEmphasisStyle: string
    _textGroupAlign: string
    _textIndent: string
    _textJustify: string
    _textOrientation: string
    _textOverflow: string
    _textShadow: string
    _textSpaceCollapse: string
    _textSpaceTrim: string
    _textSpacing: string
    _textTransform: string
    _textUnderlineOffset: string
    _textUnderlinePosition: string
    _textWrap: string
    _top: string
    _transform: string
    _transformBox: string
    _transformOrigin: string
    _transformStyle: string
    _transition: string
    _transitionDelay: string
    _transitionDuration: string
    _transitionProperty: string
    _transitionTimingFunction: string
    _translate: string
    _unicodeBidi: string
    _userSelect: string
    _verticalAlign: string
    _visibility: string
    _voiceBalance: string
    _voiceDuration: string
    _voiceFamily: string
    _voicePitch: string
    _voiceRange: string
    _voiceRate: string
    _voiceStress: string
    _voiceVolume: string
    _volume: string
    _whiteSpace: string
    _widows: string
    _width: string
    _willChange: string
    _wordBoundaryDetection: string
    _wordBoundaryExpansion: string
    _wordBreak: string
    _wordSpacing: string
    _wordWrap: string
    _wrapAfter: string
    _wrapBefore: string
    _wrapFlow: string
    _wrapInside: string
    _wrapThrough: string
    _writingMode: string
    _zIndex: string
}
